version: "3.9"
services:
  sd-ultimate-test:
    image: h3mul/sd-ultimate:latest
    environment:
      # PUBLIC_KEY: ""
      VS_SERVER_PASSWORD: testpass
      ENABLE_A1111: false
      ENABLE_INVOKEAI: false
      ENABLE_KOHYA: false
    volumes:
      - ${WORKSPACE}:/workspace
    ports:
      - 3000:3000 # a1111
      - 3010:3010 # kohya
      - 8080:8080 # vs-code
      - 9090:9090 # invokeai
      - 8188:8188 # comfyui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]